# Forge Mods.toml 配置文件
modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "template_mod"
version = "${mod_version}"
displayName = "赤石 Akaishi"
authors = "Template Author"
description = '''以「赤石」为核心的科技与生物改造模组
采集赤石矿脉与赤水晶，构筑赤能源网络，搭建矩阵反应堆发电；移植生物器官强化自身，调配药剂，建立自动化生产线。仅支持 Forge 加载器。'''

[[dependencies.template_mod]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "BOTH"

[[dependencies.template_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

# 硬依赖：Cloth Config（配置系统 GUI 基础）
[[dependencies.template_mod]]
modId = "cloth_config"
mandatory = true
versionRange = "[11,12)"
ordering = "NONE"
side = "BOTH"

# 硬依赖：Curios（饰品系统核心，玩家必须安装）
[[dependencies.template_mod]]
modId = "curios"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.template_mod]]
modId = "patchouli"
mandatory = false
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.template_mod]]
modId = "jei"
mandatory = false
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.template_mod]]
modId = "kubejs"
mandatory = false
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
