# Fusion/life matrix industrial-biotech 64x64 texture pass; preserves existing model UV and blockstates.
Add-Type -AssemblyName System.Drawing
$root=$PSScriptRoot
$tex=Join-Path $root 'common\src\main\resources\assets\akaishi\textures\block'
$prev=Join-Path $root 'gui_layouts\fusion_life_matrix_rework_preview.png'
$items=@(
 @('akaishi_fusion_controller_top','#35D6B0','controller'),@('akaishi_fusion_controller_front','#35D6B0','controller'),@('akaishi_fusion_controller_side','#247A78','side'),@('akaishi_fusion_controller_bottom','#17252C','bottom'),@('akaishi_fusion_controller_formed_front','#8CFFDA','formed'),
 @('akaishi_fusion_core','#FF8A38','core'),@('akaishi_fusion_shell','#49616B','shell'),@('akaishi_fusion_structure_glass','#64D9E8','glass'),@('akaishi_fusion_fuel_frame','#D99A38','frame'),@('akaishi_fusion_fuel_aggregator_top','#E0B34A','aggregator'),@('akaishi_fusion_fuel_aggregator_side','#9A6425','side'),@('akaishi_fusion_fuel_aggregator_bottom','#38291D','bottom'),
 @('akaishi_life_matrix_casing','#5BCF8B','casing'),@('akaishi_life_matrix_controller','#A9FFDB','controller'),@('akaishi_life_matrix_controller_formed','#D8FFF0','formed'),@('akaishi_life_matrix_structure_glass','#71E8D2','glass'),@('akaishi_life_matrix_energy_input','#4CA8FF','port'),@('akaishi_life_matrix_energy_output','#FF6389','port')
)
function Paint($name,$hex,$kind){$b=New-Object Drawing.Bitmap(64,64);$g=[Drawing.Graphics]::FromImage($b);$g.Clear([Drawing.Color]::FromArgb(255,18,25,30));$c=[Drawing.ColorTranslator]::FromHtml($hex);$dark=[Drawing.Color]::FromArgb(255,[Math]::Max(0,$c.R-55),[Math]::Max(0,$c.G-55),[Math]::Max(0,$c.B-55));$light=[Drawing.Color]::FromArgb(255,[Math]::Min(255,$c.R+45),[Math]::Min(255,$c.G+45),[Math]::Min(255,$c.B+45));$g.FillRectangle((New-Object Drawing.SolidBrush $dark),3,3,58,58);$g.FillRectangle((New-Object Drawing.SolidBrush $c),8,8,48,48);for($i=0;$i -lt 5;$i++){$g.DrawLine((New-Object Drawing.Pen $light,2),10,12+$i*10,54,12+$i*10)};if($kind -in @('core','glass','formed')){$g.FillEllipse((New-Object Drawing.SolidBrush $light),20,20,24,24);$g.DrawEllipse((New-Object Drawing.Pen $c,3),16,16,32,32)}elseif($kind -eq 'port'){$g.FillRectangle((New-Object Drawing.SolidBrush $light),18,18,28,28);$g.DrawRectangle((New-Object Drawing.Pen $dark,3),18,18,28,28)};$b.Save((Join-Path $tex ($name+'.png')),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$b.Dispose()}
foreach($i in $items){Paint $i[0] $i[1] $i[2]}
$sheet=New-Object Drawing.Bitmap(512,192);$g=[Drawing.Graphics]::FromImage($sheet);$g.Clear([Drawing.Color]::Black);for($i=0;$i -lt $items.Count;$i++){ $im=[Drawing.Image]::FromFile((Join-Path $tex ($items[$i][0]+'.png')));$g.DrawImage($im,(($i%8)*64),([Math]::Floor($i/8)*64));$im.Dispose() };$g.Dispose();$sheet.Save($prev,[Drawing.Imaging.ImageFormat]::Png);$sheet.Dispose();Write-Output "generated $($items.Count) textures; preview $prev"