# 64x64 life wireless + fusion functional texture pass. Existing JSON/model/blockstate IDs are preserved.
Add-Type -AssemblyName System.Drawing
$root=$PSScriptRoot
$tex=Join-Path $root 'common\src\main\resources\assets\akaishi\textures\block'
$out=Join-Path $root 'gui_layouts\life_wireless_fusion_rework_preview.png'
$items=@(
 @('akaishi_life_wireless_controller_front','#25B89D','controller'),@('akaishi_life_wireless_controller_top','#42D9B7','controller'),@('akaishi_life_wireless_controller_side','#176B69','side'),@('akaishi_life_wireless_controller_bottom','#102B35','bottom'),
 @('akaishi_life_wireless_core','#E06438','core'),@('akaishi_life_wireless_shell','#405A63','shell'),@('akaishi_life_wireless_structure_glass','#62D5D2','glass'),@('akaishi_life_wireless_terminal','#2B6570','terminal'),@('akaishi_life_wireless_terminal_formed','#9BFFE0','formed'),@('akaishi_life_wireless_input_port','#47A8FF','input'),@('akaishi_life_wireless_output_port','#FF557A','output'),
 @('akaishi_fusion_energy_output','#FF9A36','energy'),@('akaishi_fusion_item_input','#4CA8FF','input'),@('akaishi_fusion_item_output','#FF557A','output'),@('akaishi_fusion_cooler_frame','#55C9D1','cooler'),@('akaishi_fusion_efficiency_frame','#D8A83E','efficiency'),@('akaishi_fusion_insulation','#8B6D9E','insulation')
)
function Paint($n,$h,$k){$b=[Drawing.Bitmap]::new(64,64);$g=[Drawing.Graphics]::FromImage($b);$g.Clear([Drawing.Color]::FromArgb(255,12,20,25));$c=[Drawing.ColorTranslator]::FromHtml($h);$d=[Drawing.Color]::FromArgb(255,[Math]::Max(0,$c.R-55),[Math]::Max(0,$c.G-55),[Math]::Max(0,$c.B-55));$l=[Drawing.Color]::FromArgb(255,[Math]::Min(255,$c.R+48),[Math]::Min(255,$c.G+48),[Math]::Min(255,$c.B+48));$g.FillRectangle([Drawing.SolidBrush]::new($d),2,2,60,60);$g.FillRectangle([Drawing.SolidBrush]::new($c),7,7,50,50);$p=[Drawing.Pen]::new($l,2);for($i=0;$i -lt 6;$i++){$g.DrawLine($p,9,11+$i*9,55,11+$i*9)};if($k -in @('core','glass','formed')){$g.FillEllipse([Drawing.SolidBrush]::new($l),19,19,26,26);$g.DrawEllipse([Drawing.Pen]::new($d,3),15,15,34,34)}elseif($k -in @('input','output','energy')){$g.FillRectangle([Drawing.SolidBrush]::new($l),17,17,30,30);$g.DrawRectangle([Drawing.Pen]::new($d,3),17,17,30,30)}elseif($k -eq 'cooler'){$g.DrawRectangle([Drawing.Pen]::new($l,5),12,12,40,40);$g.DrawLine($p,12,52,52,12)}elseif($k -eq 'efficiency'){$g.DrawLine([Drawing.Pen]::new($l,5),14,48,25,30);$g.DrawLine([Drawing.Pen]::new($l,5),25,30,36,38);$g.DrawLine([Drawing.Pen]::new($l,5),36,38,51,15)}$b.Save((Join-Path $tex ($n+'.png')),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$b.Dispose()}
foreach($i in $items){Paint $i[0] $i[1] $i[2]}
$sheet=[Drawing.Bitmap]::new(512,192);$g=[Drawing.Graphics]::FromImage($sheet);$g.Clear([Drawing.Color]::Black);for($i=0;$i -lt $items.Count;$i++){$im=[Drawing.Image]::FromFile((Join-Path $tex ($items[$i][0]+'.png')));$g.DrawImage($im,(($i%8)*64),([Math]::Floor($i/8)*64));$im.Dispose()};$g.Dispose();$sheet.Save($out,[Drawing.Imaging.ImageFormat]::Png);$sheet.Dispose();Write-Output "generated $($items.Count) textures; preview $out"